#docker exec -it mongo-container mongosh -u root -p root
version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: "task-app-mongodb-container"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - "database:/data/db"

volumes:
  database:
